import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import AppReduxProvider from "./state/redux/AppReduxProvider";
import { AppThemeContextProvider } from "./state/context/AppThemeContext";
import AppBar from "@/components/AppBar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// props.children
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <AppReduxProvider>
          <AppThemeContextProvider>
          <div className="container-fluid">
            
            <AppBar/>
            <main>
              {children}
            </main>
          </div>
          </AppThemeContextProvider>
        </AppReduxProvider>
      </body>
    </html>
  );
}
